name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.1, 8.2, 8.3, 8.4]
        stability: [prefer-lowest, prefer-stable]
        laravel: [9.x, 10.x, 11.x]
        exclude:
          - laravel: 11.x
            php: 8.1

    name: L${{ matrix.laravel }} - PHP ${{ matrix.php }} - ${{ matrix.stability }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd
          tools: composer:v2
          coverage: none

      - name: Install Laravel ${{ matrix.laravel }}
        run: |
          composer create-project --prefer-dist laravel/laravel=${{ matrix.laravel }} laravel-${{ matrix.laravel }} --no-interaction

      - name: Require Lucid
        run: |
          cd laravel-${{ matrix.laravel }}
          composer config repositories.lucid '{"type": "path", "url": "$GITHUB_WORKSPACE", "options": {"symlink": true}}'
          composer require lucidarch/lucid:@dev

      - name: Run Tests
        run: |
          chmod +x $GITHUB_WORKSPACE/bin/test-commands.sh
          cp $GITHUB_WORKSPACE/bin/test-commands.sh laravel-${{ matrix.laravel }}
          cd laravel-${{ matrix.laravel }}
          ./test-commands.sh
